# Generated by Django 4.0.4 on 2022-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
