# Generated by Django 4.0.4 on 2022-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='erastusnzula@gmail.com', max_length=254, verbose_name='Enter your email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Enter message'),
        ),
    ]
