# Generated by Django 4.0.4 on 2022-05-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contact_name_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='downloads/mobile/%Y/%m/%d/')),
                ('windows', models.FileField(blank=True, default='', null=True, upload_to='downloads/windows/%Y/%m/%d/')),
                ('linux', models.FileField(blank=True, default='', null=True, upload_to='downloads/linux/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
